"""BOSS selectors are centralized because the live DOM changes frequently."""

JOB_CARD = (".job-card-wrapper", ".job-list-box .job-card-box")
JOB_TITLE = (".job-name", "[class*='job-name']")
COMPANY_NAME = (".company-name a", ".company-name")
SALARY = (".salary", ".job-salary")
JOB_LINK = ("a[href*='/job_detail/']", ".job-card-left a")
JOB_LOCATION = (".job-area", ".job-info .job-area")
JOB_TAGS = (".tag-list span", ".job-card-footer .tag-list span")
CARD_DESCRIPTION = (".job-card-desc", ".job-card-footer")

DETAIL_DESCRIPTION = (".job-sec-text", ".job-detail-section .text", ".job-detail")
RECRUITER_NAME = (".boss-info .name", ".boss-name", ".job-boss-info .name")
RECRUITER_ACTIVITY = (".boss-info .boss-active-time", ".boss-active-time")
START_CHAT = ("a[ka='job_detail_chat']", "a.btn-startchat:has-text('立即沟通')", "a:has-text('立即沟通')")
CONTINUE_CHAT = ("a.btn-startchat:has-text('继续沟通')", "a:has-text('继续沟通')")
CHAT_INPUT = ("#chat-input", ".chat-input textarea", "div.chat-editor textarea", "div.edit-area [contenteditable='true']")
SEND_BUTTON = ("button.btn-send:has-text('发送')", "button:has-text('发送')", ".chat-op button[type='submit']")
OUTGOING_MESSAGE = (".message-item.item-myself", ".message-item.is-self", ".chat-message.me")
INCOMING_MESSAGE = (".message-item:not(.item-myself):not(.is-self)", ".chat-message:not(.me)")
SYSTEM_MESSAGE = (".system-message", ".message-system", ".notice-message")
RESUME_BUTTON = ("button:has-text('发送简历')", "a:has-text('发送简历')", "button:has-text('发简历')")
FILE_INPUT = ("input[type='file']",)
CONFIRM_SEND = ("button:has-text('确认发送')", "button:has-text('确定')")
ATTACHMENT_EVIDENCE = (".message-item.item-myself:has-text('简历')", ".message-item.item-myself .file-name")

CAPTCHA = ("#captcha", ".slide-verify", ".geetest_panel", ".captcha-wrapper", "div.dialog-container:has(canvas)")
CAPTCHA_TEXT = ("请完成安全验证", "滑动验证", "图形验证", "安全检测")
DAILY_LIMIT_TEXT = ("今日沟通人数已达上限", "今日投递次数已用完", "今天的机会已用完")
LOGIN_PATH_MARKERS = ("/web/user", "/user/login")
